### ISSUE TITLE
Is it possible post metrics without `service.` prefix?

### ISSUE THREAD

**Issue by astj** [a-know/mackerel-remora#1]
Hi. Thank you for nice product!

I've found mackerel-remora adds `service.` prefix to given metric names. (https://github.com/a-know/mackerel-remora/blob/master/metric/plugin.go#L14 / https://github.com/a-know/mackerel-remora/blob/master/metric/plugin.go#L48)
But we've been posting our service metrics without `service.` prefix, therefore I cannot keep using same service metric graphs while migrating from traditional crontab + mkr throw combinations.

Do you have any idea to solve this problem?  (Hopefully I'd like to request some feature to omit `service.` prefix)

**Comment by a-know** [comment]
Thank you for the issue!

I would like to support an option `omitNamePrefix` . 🤔 

```
apibase: <apibase>
apikey: <apikey>
root: <rootdir>
plugin:
  servicemetrics:
    <servicename>:
      <settingname>:
        command: <command>
        user: <user>
        omitNamePrefix: true
        env:
          <envkey>: <envvalue>
```
